name: Node Continuous Integration
on: push
jobs:   
    build-node:
        name: Build Node
        runs-on: ubuntu-latest
        container: node:20.8.0
        steps:
            - run: node --version
            - run: npm --version